config/authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup', views.signup, name='signup'),
    path('signin', auth_views.LoginView.as_view(template_name='authentication/signin.html'), name='signin'),
    path('signout', auth_views.LogoutView.as_view(template_name='authentication/signout.html'), name='signout'),    
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('', include('authentication.urls')),
    
]

config/events/urls.py
from django.urls import path
from . import views
app_name = "events"

urlpatterns = [
    path('', views.upcoming_events, name='upcoming_events'),
    path('add-event', views.add_event, name='add_event'),
    path('upcoming-events', views.user_upcoming_events_list, name='upcoming-events'),
    path('following-list', views.user_following_list, name='following-list'),
    path('users', views.UserAPIView.as_view(), name='users'),
    path('attendances', views.AttendanceAPIView.as_view(), name='attendances'),
    path('followings', views.FollowingAPIView.as_view(), name='followings'),
    
]

config/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="{% static 'bootstrap4/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap4/overrides.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
    <header class="site-header">
        <div class="navbar navbar-expand-md nav-tabs navbar-default">
          <div class="container d-flex justify-content-between">
            <a href="{% url 'authentication:home' %}" class="navbar-brand d-flex align-items-center">
              <strong>Musly</strong>
            </a>
            
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'events:add_event' %}">Add event</a>
                  <a class="nav-item nav-link" href="{% url 'authentication:signout' %}">Sign Out</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'authentication:signin' %}">Sign In</a>
                  <a class="nav-item nav-link active" href="{% url 'authentication:signup' %}">Sign Up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </header>
    <main role="main" class="container mt-5">
        {% block content %}
        {% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap4/js/bootstrap.min.js' %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>